export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_GOOGLE = 'LOGIN_REQUEST_GOOGLE';
export const LOGIN_REQUEST_FACEBOOK = 'LOGIN_REQUEST_FACEBOOK';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';